# Generated by Django 3.0.6 on 2020-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_documents',
            field=models.BooleanField(default=False, verbose_name='Блок документы'),
        ),
    ]
