# Generated by Django 3.0.4 on 2020-03-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_auto_20200325_1929'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCategroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Количественные категории')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вид поддержки')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, verbose_name='Название проекта')),
                ('description', models.TextField(max_length=3000, verbose_name='Краткое описание проекта (деятельности в рамках проекта)')),
                ('geography', models.TextField(max_length=1000, verbose_name='География проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала реализации проекта')),
                ('finish_date', models.DateField(verbose_name='Дата окончания реализации проекта')),
                ('social_significance', models.TextField(max_length=5000, verbose_name='Обоснование социальной значимости проекта')),
                ('info_support', models.TextField(max_length=1000, verbose_name='Как будет организовано информационное сопровождение проекта')),
                ('quality_results', models.TextField(max_length=1000, verbose_name='Качественные результаты')),
                ('further_progress', models.TextField(max_length=2500, verbose_name='Дальнейшее развитие проекта')),
                ('sources', models.TextField(max_length=500, verbose_name='Источники ресурсного обеспечения проекта в дальнейшем')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Конкурс')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Direction', verbose_name='Грантовое направление, которому преимущественно соответствует планируемая деятельность по проекту')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Subject', verbose_name='Тематика грантового направления, которому преимущественно соответствует планируемая деятельность по проекту')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=1000, verbose_name='Url')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='projects', verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Описание проекта',
                'verbose_name_plural': 'Описание проекта',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид поддержки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
                ('supports', models.ManyToManyField(to='contest.Direction', verbose_name='Виды поддержки')),
            ],
        ),
        migrations.CreateModel(
            name='LetterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='projects', verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Письмо поддержки',
                'verbose_name_plural': 'Письма поддержки',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='Задача проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=600, verbose_name='Цель проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='CountResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.CountCategroy', verbose_name='Категория')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
    ]
