# Generated by Django 3.0.4 on 2020-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'Новый'), ('on_exam', 'На экспертизе'), ('win', 'Выиграл'), ('reject', 'Не выиграл')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
