# Generated by Django 3.0.4 on 2020-04-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200402_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания реализации проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала реализации проекта'),
        ),
    ]
