# Generated by Django 3.0.4 on 2020-04-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200402_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, choices=[('srednee_obshee', 'Среднее общее'), ('srednee_proff', 'Среднее профессиональное'), ('nezakonchennoe_vusshee', 'Не законченное высшее'), ('vusshee', 'Высшее'), ('bolee_odngogo_vishego', 'Более одного высшего'), ('uchenuy', 'Есть ученая степень')], max_length=32, verbose_name='Оразование')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя проекта в организации-заявителе')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Ученая степень')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Электронная почта')),
                ('info', models.TextField(blank=True, max_length=600, verbose_name='Дополнительные сведения')),
                ('photo', models.ImageField(upload_to='projects', verbose_name='Изображение')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, choices=[('srednee_obshee', 'Среднее общее'), ('srednee_proff', 'Среднее профессиональное'), ('nezakonchennoe_vusshee', 'Не законченное высшее'), ('vusshee', 'Высшее'), ('bolee_odngogo_vishego', 'Более одного высшего'), ('uchenuy', 'Есть ученая степень')], max_length=32, verbose_name='Оразование')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя проекта в организации-заявителе')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('info', models.TextField(blank=True, max_length=600, verbose_name='Дополнительные сведения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='TravelConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traget', models.CharField(max_length=255, verbose_name='Цель поездки и место назначения (если оно определено)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Расходы на одного работника (в рублях)')),
                ('workers_count', models.IntegerField(verbose_name='Количество работников')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (по всем командируемым, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Заработная плата в месяц (в рублях, включая НДФЛ)')),
                ('month_count', models.IntegerField(verbose_name='Количество месяцев (не более 18 месяцев)')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (за весь период, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemberOrgaziation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('edu', 'Образовательные организации и специальности'), ('work', 'Место работы')], max_length=32, verbose_name='Тип')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность/Специальность')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Год начала')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Год окончания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectManager', verbose_name='Менеджер проекта')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectMember', verbose_name='Участник проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255, verbose_name='Функция в проекте или содержание услуг (работ)')),
                ('payout', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Вознаграждение по одному договору (в рублях, включая НДФЛ)')),
                ('contracts_count', models.IntegerField(verbose_name='Количество договоров')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (по всем договорам, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Взнос')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Общая сумма (в рублях)')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (за весь период, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='GenericConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('office', 'Офисные расходы'), ('equipment', 'Приобретение, аренда специализированного оборудования, инвентаря и сопутствующие расходы'), ('devel', 'Разработка и поддержка сайтов, информационных систем и иные аналогичные расходы'), ('legal', 'Оплата юридических, информационных, консультационных услуг и иные аналогичные расходы'), ('events', 'Расходы на проведение мероприятий'), ('publishing', 'Издательские, полиграфические и сопутствующие расходы'), ('other', 'Прочие прямые расходы')], max_length=32, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование расходов')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость единицы (в рублях)')),
                ('items_count', models.IntegerField(verbose_name='Кол-во единиц')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (по всем командируемым, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_on_found', models.BooleanField(verbose_name='Целесообразно ли размещение сведений о мероприятии на информационных ресурсах фонда?')),
                ('name', models.TextField(verbose_name='Мероприятие, его содержание, место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('finish_date', models.DateField(verbose_name='Дата окончания')),
                ('result', models.TextField(verbose_name='Ожидаемые результаты')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Job', verbose_name='Решаемая задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectManager', verbose_name='Менеджер проекта'),
        ),
    ]
