# Generated by Django 3.0.4 on 2020-04-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200403_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salary', 'Оплата труда штатных работников'), ('payouts', 'Выплаты физическим лицам (за исключением индивидуальных предпринимателей) оказание ими услуг (выполнение работ) по гражданско-правовым договорам'), ('office', 'Офисные расходы'), ('travel', 'Командировочные расходы'), ('equipment', 'Приобретение, аренда специализированного оборудования, инвентаря и сопутствующие расходы'), ('devel', 'Разработка и поддержка сайтов, информационных систем и иные аналогичные расходы'), ('legal', 'Оплата юридических, информационных, консультационных услуг и иные аналогичные расходы'), ('events', 'Расходы на проведение мероприятий'), ('publishing', 'Издательские, полиграфические и сопутствующие расходы'), ('other', 'Прочие прямые расходы')], max_length=32, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование расходов')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость единицы (в рублях)')),
                ('items_count', models.IntegerField(verbose_name='Кол-во единиц')),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Софинансирование (по всем командируемым, в рублях)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Расходы проекта',
                'verbose_name_plural': 'Расходы проекта',
            },
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='project',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='project',
        ),
        migrations.RemoveField(
            model_name='travelconst',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Цель проекта', 'verbose_name_plural': 'Цели проекта'},
        ),
        migrations.AlterModelOptions(
            name='projectmanager',
            options={'verbose_name': 'Менеджер проекта', 'verbose_name_plural': 'Менеджеры проекта'},
        ),
        migrations.DeleteModel(
            name='GenericConst',
        ),
        migrations.DeleteModel(
            name='Payouts',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='TravelConst',
        ),
    ]
