# Generated by Django 3.0.4 on 2020-04-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200417_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterfile',
            name='file',
            field=models.FileField(upload_to='projects', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='supports',
            field=models.ManyToManyField(to='project.PartnerSupport', verbose_name='Виды поддержки'),
        ),
        migrations.AlterField(
            model_name='presentationfile',
            name='file',
            field=models.FileField(upload_to='projects', verbose_name='Файл'),
        ),
    ]
