# Generated by Django 3.0.4 on 2020-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200420_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер проекта', 'verbose_name_plural': 'Партнеры проекта'},
        ),
        migrations.AlterModelOptions(
            name='partnersupport',
            options={'verbose_name': 'Вид поддержки', 'verbose_name_plural': 'Виды поддержки'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Партнер'),
        ),
    ]
