# Generated by Django 3.0.4 on 2020-04-21 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_auto_20200420_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experts',
            field=models.ManyToManyField(related_name='experts', to=settings.AUTH_USER_MODEL, verbose_name='Эксперты'),
        ),
    ]
