# Generated by Django 3.0.5 on 2020-04-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_experts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn', models.CharField(blank=True, max_length=255, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=255, verbose_name='КПП')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование организации')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование организации')),
                ('egrul_file', models.FileField(upload_to='projects', verbose_name='Сведения из ЕГРЮЛ')),
                ('ustav_file', models.FileField(upload_to='projects', verbose_name='Файл устава')),
            ],
            options={
                'verbose_name': 'Организация заявитель',
                'verbose_name_plural': 'Организации заявители',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects', verbose_name='Файл')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ об организации',
                'verbose_name_plural': 'Документы об организации',
            },
        ),
    ]
