# Generated by Django 3.0.5 on 2020-04-30 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcost',
            name='type',
            field=models.CharField(choices=[('salary', 'Оплата труда штатных работников'), ('insurance', 'Страховые взносы'), ('payouts', 'Выплаты физическим лицам (за исключением индивидуальных предпринимателей) оказание ими услуг (выполнение работ) по гражданско-правовым договорам'), ('office', 'Офисные расходы'), ('travel', 'Командировочные расходы'), ('equipment', 'Приобретение, аренда специализированного оборудования, инвентаря и сопутствующие расходы'), ('devel', 'Разработка и поддержка сайтов, информационных систем и иные аналогичные расходы'), ('legal', 'Оплата юридических, информационных, консультационных услуг и иные аналогичные расходы'), ('events', 'Расходы на проведение мероприятий'), ('publishing', 'Издательские, полиграфические и сопутствующие расходы'), ('other', 'Прочие прямые расходы')], max_length=32, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Образовательные учреждения'), ('work', 'Место работы')], default='education', max_length=32, verbose_name='Тип')),
                ('organization', models.TextField(max_length=300, verbose_name='Организация')),
                ('position', models.CharField(max_length=100, verbose_name='Должность/Специальность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('finish_date', models.DateField(verbose_name='Дата окончания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectManager', verbose_name='Руководитель проекта')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectMember', verbose_name='Участник проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
    ]
