# Generated by Django 3.0.5 on 2020-04-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200430_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='supports',
        ),
        migrations.AddField(
            model_name='partner',
            name='supports',
            field=models.TextField(blank=True, verbose_name='Виды поддержки'),
        ),
    ]
