# Generated by Django 3.0.5 on 2020-04-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200501_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerSupport',
        ),
    ]
