# Generated by Django 3.0.5 on 2020-05-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_project_quant_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='quant_results',
        ),
        migrations.CreateModel(
            name='QuantResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=600, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Количественный результат',
                'verbose_name_plural': 'Количественные результаты',
            },
        ),
    ]
