# Generated by Django 3.0.5 on 2020-05-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20200501_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('letter', 'Письма поддержки'), ('presentation', 'Описание проекта'), ('organization', 'Страховые взносы'), ('manager', 'Дополнительные документы об организации')], max_length=32, verbose_name='Тип')),
                ('file', models.FileField(upload_to='projects', verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationfile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='presentationfile',
            name='project',
        ),
        migrations.DeleteModel(
            name='LetterFile',
        ),
        migrations.DeleteModel(
            name='OrganizationFile',
        ),
        migrations.DeleteModel(
            name='PresentationFile',
        ),
    ]
