# Generated by Django 3.0.5 on 2020-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200506_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Учёное звание, учёная степень руководителя проекта (если имеется):'),
        ),
    ]
