# Generated by Django 3.0.5 on 2020-05-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_projectmanager_academic_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='egrul_file',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ustav_file',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='6. Адрес (место нахождения) организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='13.1. Адрес электронной почты для внешних коммуникаций'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='7. Фактическое место нахождения организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='8. Адрес для направления организации юридически значимых сообщений'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='13. Адрес электронной почты для направления организации юридически значимых сообщений'),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_activities',
            field=models.TextField(blank=True, verbose_name='9. Основные виды деятельности организации:'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='15.2. Дата рождения руководителя'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager_correct',
            field=models.BooleanField(blank=True, default=True, verbose_name='15.1. Данные о руководителе совпадают с данными ЕГРЮЛ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager_fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='15. ФИО руководителя организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='12. Контактный телефон организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='5.2. Дата регистрации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='social',
            field=models.TextField(blank=True, verbose_name='14.2. Группы в соц. сетях'),
        ),
        migrations.AddField(
            model_name='organization',
            name='web',
            field=models.CharField(blank=True, max_length=100, verbose_name='14.1. Веб-сайт'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='type',
            field=models.CharField(choices=[('project', 'Для проекта'), ('organization', 'Для организации')], default='project', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='4. Полное наименование организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='2. ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, verbose_name='3. КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=255, verbose_name='1. ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='5. Сокращенное наименование организации'),
        ),
    ]
