# Generated by Django 3.0.5 on 2020-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20200506_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='commercial_grants',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='взносы, пожертвования российских коммерческих организаций'),
        ),
        migrations.AddField(
            model_name='organization',
            name='dividends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='внереализационные доходы (дивиденды, проценты по депозитам и т.п.)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='employees_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='23. Количество штатных работников'),
        ),
        migrations.AddField(
            model_name='organization',
            name='federal_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='средства, полученные из федерального бюджета'),
        ),
        migrations.AddField(
            model_name='organization',
            name='foreign_grants',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='гранты, взносы, пожертвования иностранных организаций и иностранных граждан'),
        ),
        migrations.AddField(
            model_name='organization',
            name='local_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='средства, полученные из местных бюджетов'),
        ),
        migrations.AddField(
            model_name='organization',
            name='media_publications',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации в СМИ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='вступительные, членские и иные взносы, пожертвования российских граждан'),
        ),
        migrations.AddField(
            model_name='organization',
            name='non_commercial_grants',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='гранты, взносы, пожертвования российских некоммерческих организаций (исключая президентские гранты)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='прочие доходы'),
        ),
        migrations.AddField(
            model_name='organization',
            name='presidential_grants',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='президентские гранты'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='средства, полученные из бюджетов субъектов Российской Федерации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='доходы (выручка) от реализации товаров, работ, услуг, имущественных прав'),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='26. Общая сумма расходов организации за предыдущий год'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volunteers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='24. Количество добровольцев'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_activities',
            field=models.TextField(blank=True, verbose_name='9. Основные виды деятельности организации'),
        ),
    ]
