# Generated by Django 3.0.6 on 2020-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200506_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='projects', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='media_publications',
            field=models.TextField(blank=True, null=True, verbose_name='30. Публикации в СМИ'),
        ),
    ]
