# Generated by Django 3.0.6 on 2020-05-06 22:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200506_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='beneficiaries_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='27. Количество благополучателей за предыдущий год (с января по декабрь): физические лица, юридические лица'),
        ),
        migrations.AddField(
            model_name='organization',
            name='success_projects',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
