# Generated by Django 3.0.6 on 2020-05-06 23:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20200507_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main_activities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
