# Generated by Django 3.0.6 on 2020-05-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_organization_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='support_type',
            field=models.CharField(blank=True, choices=[('type1', 'Организация состоит в реестре исполнителей общественно-полезных услуг Минюста'), ('type2', 'Организация оказывает информационную, консультационную, методическую, образовательную, экспертную и иную поддержку социально ориентированным некоммерческим организациям')], max_length=32, null=True, verbose_name='Приоритетная поддержка организации'),
        ),
    ]
