# Generated by Django 3.0.6 on 2020-05-13 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0031_organization_support_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Подготовка'), ('new', 'На модерации'), ('fix', 'На доработку'), ('on_exam', 'На экспертизе'), ('win', 'Выиграл'), ('win', 'Выиграл'), ('reject', 'Отклонен')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('internal', 'Внутренние'), ('external', 'Общедоступные')], default='internal', max_length=32, verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект')),
            ],
        ),
    ]
