# Generated by Django 3.0.6 on 2020-05-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '__first__'),
        ('project', '0032_auto_20200513_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experts',
            field=models.ManyToManyField(related_name='experts', to='expert.Expert', verbose_name='Эксперты'),
        ),
    ]
