# Generated by Django 3.0.6 on 2020-05-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20200514_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
