# Generated by Django 3.0.6 on 2020-05-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20200514_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (место нахождения) организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiaries_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество благополучателей за предыдущий год (с января по декабрь): физические лица, юридические лица'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес электронной почты для внешних коммуникаций'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employees_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество штатных работников'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фактическое место нахождения организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес для направления организации юридически значимых сообщений'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес электронной почты для направления организации юридически значимых сообщений'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения руководителя'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager_correct',
            field=models.BooleanField(blank=True, default=True, verbose_name='Данные о руководителе совпадают с данными ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager_fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='media_publications',
            field=models.TextField(blank=True, null=True, verbose_name='Публикации в СМИ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество членов (участников) организации: физических лиц, юридических лиц:'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='1Контактный телефон организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращенное название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='social',
            field=models.TextField(blank=True, verbose_name='Группы в соц. сетях'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Общая сумма расходов организации за предыдущий год'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='volunteers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество добровольцев'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web',
            field=models.CharField(blank=True, max_length=100, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'На проверке'), ('fix', 'На доработку'), ('on_exam', 'На экспертизе'), ('win', 'Проект, получивший поддержку'), ('not_win', 'Проект, не получивший поддержку'), ('reject', 'Отклонена')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
