# Generated by Django 3.0.6 on 2020-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20200516_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Отчет'),
        ),
    ]
