# Generated by Django 3.0.6 on 2020-05-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20200516_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='in_present',
            field=models.BooleanField(default=False, verbose_name='По настоящее время'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
    ]
