# Generated by Django 3.0.6 on 2020-05-16 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20200516_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cost',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
