# Generated by Django 3.0.6 on 2020-05-17 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_merge_20200516_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты для внешних коммуникаций'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_email',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты для направления организации юридически значимых сообщений'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон организации'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='email',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
    ]
