# Generated by Django 3.0.6 on 2020-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20200517_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='best',
            field=models.BooleanField(default=False, verbose_name='Лучший проект'),
        ),
    ]
