# Generated by Django 3.0.6 on 2020-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_project_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'На проверке'), ('fix', 'На доработку'), ('reject', 'Отклонена'), ('approved', 'Принят')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/2020', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('new', 'На проверке'), ('fix', 'На доработку'), ('on_exam', 'На экспертизе'), ('win', 'Победитель конкурса'), ('not_win', 'Проект, не получивший поддержку'), ('reject', 'Отклонена')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/2020', verbose_name='Файл'),
        ),
    ]
