# Generated by Django 3.0.6 on 2020-05-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20200520_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Отчет'),
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/reports/2020', verbose_name='Файл')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Event', verbose_name='Мероприятие')),
            ],
        ),
    ]
