# Generated by Django 3.0.6 on 2020-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20200527_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
    ]
