# Generated by Django 3.0.6 on 2020-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20200605_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='employees_count',
            field=models.IntegerField(default=0, verbose_name='Количество штатных работников'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members_count',
            field=models.IntegerField(default=0, verbose_name='Количество членов (участников) организации: физических лиц, юридических лиц:'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='volunteers_count',
            field=models.IntegerField(default=0, verbose_name='Количество добровольцев'),
        ),
    ]
