# Generated by Django 3.0.6 on 2020-06-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_auto_20200613_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['content']},
        ),
    ]
