# Generated by Django 3.0.11 on 2021-02-09 17:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20200619_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='checklist',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
