# Generated by Django 3.0.14 on 2021-04-30 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_auto_20210210_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to='projects/reports/2021', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/2021', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/2021', verbose_name='Файл'),
        ),
    ]
