# Generated by Django 3.0.14 on 2021-04-30 06:45
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    Job = apps.get_model('project', 'Job')
    for row in Job.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20210430_1544'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
