# Generated by Django 3.0.14 on 2021-05-04 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20210504_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
