# Generated by Django 3.0.14 on 2021-05-04 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_auto_20210504_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
