# Generated by Django 3.0.14 on 2021-05-04 05:01
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    ProjectMember = apps.get_model('project', 'ProjectMember')
    for row in ProjectMember.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_projectmember_guid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
