# Generated by Django 3.0.14 on 2021-05-04 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_auto_20210504_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='event',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
