# Generated by Django 3.0.14 on 2021-05-04 05:23
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    Event = apps.get_model('project', 'Event')
    for row in Event.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_auto_20210504_1423'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
