# Generated by Django 3.0.14 on 2021-05-04 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_auto_20210504_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
