# Generated by Django 3.0.14 on 2021-05-04 05:46
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    GenericCost = apps.get_model('project', 'GenericCost')
    for row in GenericCost.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_auto_20210504_1446'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
