# Generated by Django 3.0.14 on 2021-05-04 05:56
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Institution = apps.get_model('project', 'Institution')
    for row in Institution.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0081_institution_guid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
