# Generated by Django 3.0.14 on 2021-05-04 06:11
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    QuantResult = apps.get_model('project', 'QuantResult')
    for row in QuantResult.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0084_quantresult_guid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
