# Generated by Django 3.0.14 on 2021-05-04 06:20
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Geography = apps.get_model('project', 'Geography')
    for row in Geography.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0087_geography_guid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
