# Generated by Django 3.0.14 on 2021-05-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0091_auto_20210519_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcost',
            name='name',
            field=models.TextField(verbose_name='Наименование расходов'),
        ),
    ]
