# Generated by Django 3.0.14 on 2021-06-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0092_auto_20210519_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание проекта (деятельности в рамках проекта)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='further_progress',
            field=models.TextField(blank=True, verbose_name='Дальнейшее развитие проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='info_support',
            field=models.TextField(blank=True, verbose_name='Как будет организовано информационное сопровождение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quality_results',
            field=models.TextField(blank=True, verbose_name='Качественные результаты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='social_significance',
            field=models.TextField(blank=True, verbose_name='Обоснование социальной значимости проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=models.TextField(blank=True, verbose_name='Источники ресурсного обеспечения проекта в дальнейшем'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название проекта'),
        ),
    ]
