# Generated by Django 3.0.14 on 2021-08-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0094_auto_20210810_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Срок сдачи отчетности'),
        ),
    ]
