# Generated by Django 3.0.14 on 2021-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0095_project_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingexpense',
            name='overall',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportingexpense',
            name='planned',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportingexpense',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='reportingexpense',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
    ]
