# Generated by Django 3.0.14 on 2021-09-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0096_auto_20210902_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingevent',
            name='fulfillment',
            field=models.CharField(max_length=10000),
        ),
    ]
