# Generated by Django 3.0.14 on 2021-09-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0097_auto_20210916_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingevent',
            name='name',
            field=models.TextField(max_length=1000, verbose_name='Мероприятие, его содержание, место проведения'),
        ),
    ]
