# Generated by Django 3.0.14 on 2022-02-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0098_auto_20210930_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Краткое описание исполнения проекта со следующими пояснениями: Необходимо загрузить текст на русском языке, состоящий из не более 3000 знаков содержащий краткое описание реализации проекта (- цели, задачи, - описание проекта,- руководитель проекта,- предыстория реализации проекта, - дальнейшее развитие проекта, - какие мероприятия проведены, - кто участвовал в реализации инициативы и др.). ')),
                ('beneficiaries_count', models.IntegerField(default=0, verbose_name='Количество благополучателей по итогам реализации проекта')),
                ('volunteers_count', models.IntegerField(default=0, verbose_name='Количество добровольцев, привлеченных к реализации проекта')),
                ('self_co_financing', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Размер софинансирования проекта из собственных средств')),
                ('targets', models.TextField(verbose_name='Достижение целевых показателей (Краткая информация о достижении показателей указанных в соглашении)')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Объем средств, дополнительно привлеченных на реализацию проекта (включая примерную оценку труда добровольцев, безвозмездно полученных товаров, работ, услуг, имущественных прав) с краткой аналитической информацией об источнике финансирования')),
                ('links', models.TextField(verbose_name='Информационная открытость организации, освещение мероприятий проекта. Загружаются активные ссылки на статьи, сюжеты о мероприятиях проекта, размещенные в интернет ресурсах, а также наименование и выходные данные размещенные в печатных изданиях, журналах, газетах.')),
            ],
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='file',
            field=models.FileField(upload_to='projects/agreements/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to='projects/reports/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='reportingeventfile',
            name='file',
            field=models.FileField(upload_to='projects/reports/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='reportingexpensefile',
            name='file',
            field=models.FileField(upload_to='projects/reports/2022', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='reportingindicatorfile',
            name='file',
            field=models.FileField(upload_to='projects/reports/2022', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='ReportingBestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'photo'), (1, 'doc')])),
                ('file', models.FileField(upload_to='projects/reports/2022', verbose_name='Файл')),
                ('reporting_best', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.ReportingBest')),
            ],
        ),
        migrations.AddField(
            model_name='reportingbest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект'),
        ),
    ]
