# Generated by Django 3.0.14 on 2022-02-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0099_auto_20220214_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingbest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bests', to='project.Project', verbose_name='Проект'),
        ),
    ]
