# Generated by Django 3.0.6 on 2020-05-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200516_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
