# Generated by Django 3.0.14 on 2022-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200716_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='for_munobr',
            field=models.BooleanField(default=False, verbose_name='Для мун. обр'),
        ),
    ]
