# Generated by Django 3.0.14 on 2022-06-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_for_munobr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='for_munobr',
        ),
    ]
