version: '3'

services:
  db:
    image: postgres:12.2
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  web:
    build: ./src
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
