version: '3'

services:
  db:
    image: postgres:12.2
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
  web:
    build: ./src
    command: ["./wait-for-it.sh", "db:5432", "--", "gunicorn", "grants.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "${GUNICORN_TIMEOUT}"]
    volumes:
      - ./src:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
        - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
