# Generated by Django 3.0.11 on 2021-02-01 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН')),
                ('full_name', models.CharField(blank=True, max_length=2048, verbose_name='Полное название организации')),
                ('short_name', models.CharField(blank=True, max_length=1024, verbose_name='Сокращенное название организации')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('basic', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('analytics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('egr_details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['inn'],
            },
        ),
    ]
