# Generated by Django 3.0.11 on 2021-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='file_egr',
            field=models.FileField(blank=True, null=True, upload_to='contur/2021', verbose_name='Файл'),
        ),
    ]
