# Generated by Django 3.0.11 on 2021-02-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contur', '0002_organization_file_egr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=255, unique=True, verbose_name='ОГРН'),
        ),
    ]
