# Generated by Django 3.0.11 on 2021-02-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contur', '0003_auto_20210202_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='request_ver',
            field=models.CharField(blank=True, max_length=100, verbose_name='Версия запроса'),
        ),
    ]
