# Generated by Django 3.0.14 on 2022-02-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contur', '0004_organization_request_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='file_egr',
            field=models.FileField(blank=True, null=True, upload_to='contur/2022', verbose_name='Файл'),
        ),
    ]
