# Generated by Django 3.0.14 on 2022-02-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contur', '0005_auto_20220214_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Сокращенное название организации'),
        ),
    ]
