# Generated by Django 3.0.6 on 2020-05-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
    ]
