# Generated by Django 3.0.4 on 2020-03-13 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='ЧПУ')),
                ('img', models.ImageField(upload_to='directions', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Направление конкурса',
                'verbose_name_plural': 'Направления конкурса',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('order_field', models.IntegerField()),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Тематику направления',
                'verbose_name_plural': 'Тематики направления',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('opened', 'Идет прием заявок'), ('closed', 'Прием заявок закрыт')], default='new', max_length=32)),
                ('title', models.CharField(max_length=255, verbose_name='Название конкурса')),
                ('content', models.TextField(verbose_name='Описание')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('directions', models.ManyToManyField(to='contest.Direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
    ]
