# Generated by Django 3.0.4 on 2020-04-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200325_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Критерии оценки заявок на участие в конкурсе')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col500', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='не более 500тыс. рублей')),
                ('col1000', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='свыше 500 тыс. рублей и не более 1 млн рублей')),
                ('col3000', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='свыше 1 млн рублей и не более 3 млн рублей')),
                ('colinf', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='свыше 3 млн рублей')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Contest', verbose_name='Конкурс')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Criteria', verbose_name='Ктритерия оценки')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
    ]
