# Generated by Django 3.0.4 on 2020-04-21 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_project_experts'),
        ('contest', '0003_coefficient_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coefficient',
            options={'verbose_name': 'Коэффициент значимости', 'verbose_name_plural': 'Коэффициенты значимости'},
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Criteria', verbose_name='Критерия оценки'),
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('finished', 'Оценочный лист заполнен')], default='new', max_length=32, verbose_name='Статус')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Contest', verbose_name='Конкурс')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Criteria', verbose_name='Критерий оценки')),
                ('score_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.ScoreSheet', verbose_name='Оценочный лист')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценочный лист',
            },
        ),
    ]
