# Generated by Django 3.0.5 on 2020-04-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20200421_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='scoresheet',
            options={'verbose_name': 'Оценочный лист', 'verbose_name_plural': 'Оценочные листы'},
        ),
    ]
