# Generated by Django 3.0.6 on 2020-05-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200428_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.Criteria', verbose_name='Критерий оценки'),
        ),
    ]
