# Generated by Django 3.0.6 on 2020-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20200512_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация по порядку выставления баллов'),
        ),
    ]
