# Generated by Django 3.0.6 on 2020-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_criteria_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация по порядку выставления баллов'),
        ),
    ]
