# Generated by Django 3.0.6 on 2020-05-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '__first__'),
        ('contest', '0008_auto_20200513_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresheet',
            options={'ordering': ['-created_on'], 'verbose_name': 'Оценочный лист', 'verbose_name_plural': 'Оценочные листы'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Expert', verbose_name='Автор'),
        ),
    ]
