# Generated by Django 3.0.6 on 2020-05-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20200514_1612'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0009_auto_20200514_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Criteria', verbose_name='Критерий оценки'),
        ),
        migrations.AlterField(
            model_name='score',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Criteria', verbose_name='Критерий оценки'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ScoreSheet', verbose_name='Оценочный лист'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('finished', 'Завершен')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
