# Generated by Django 3.0.6 on 2020-05-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20200517_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
