# Generated by Django 3.0.6 on 2020-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20200518_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='additional_score1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Если организация состоит в реестре исполнителей общественно полезных услуг'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='additional_score2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Если Заявитель является организацией, оказывающей информационную, консультационную, методическую, образовательную, экспертную и иную поддержку социально ориентированным некоммерческим организациям, возглавляющим рейтинг эффективности деятельности за предыдущий отчетный период, разработанного Уполномоченным органом, размещаемом на Портале'),
        ),
    ]
