# Generated by Django 3.0.6 on 2020-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_auto_20200519_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='status',
            field=models.CharField(choices=[('new', 'На экспертизе'), ('finished', 'Завершен')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
