# Generated by Django 3.0.6 on 2020-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_scoresheet_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='result',
            field=models.CharField(blank=True, choices=[('good', 'проект хороший и безусловно рекомендуется к поддержке'), ('no_bad', 'проект в целом неплохой, но в нем есть недочеты, которые не позволяют сделать однозначный вывод о целесообразности поддержки проекта'), ('bad', 'проект не рекомендуется к поддержке')], max_length=32, null=True, verbose_name='Вывод'),
        ),
    ]
