# Generated by Django 3.0.6 on 2020-05-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20200521_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='commission', verbose_name='Фото')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.TextField(verbose_name='Должность')),
                ('order_field', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
        ),
    ]
