# Generated by Django 3.0.6 on 2020-05-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'члена комиссии', 'verbose_name_plural': 'Координационная комиссия'},
        ),
    ]
