# Generated by Django 3.0.6 on 2020-08-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0029_auto_20200822_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='updated_on',
            field=models.DateTimeField(verbose_name='Обновлен'),
        ),
    ]
