# Generated by Django 3.0.6 on 2020-11-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0030_auto_20200822_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coefficient',
            options={'ordering': ['criteria__title'], 'verbose_name': 'Коэффициент значимости', 'verbose_name_plural': 'Коэффициенты значимости'},
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Конкурс')),
            ],
            options={
                'verbose_name': 'Срок сдачи отчетности',
                'verbose_name_plural': 'Сроки сдачи отчетности',
            },
        ),
    ]
