# Generated by Django 3.0.6 on 2020-11-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0031_auto_20201117_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportperiod',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest', verbose_name='Конкурс'),
        ),
    ]
