# Generated by Django 3.0.14 on 2021-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0032_auto_20201117_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='boss',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('opened', 'Идет прием заявок'), ('tech_work', 'Идут подготовительные работы'), ('check', 'Идет проверка'), ('on_exam', 'Идет независимая экспертиза'), ('closed', 'Конкурс завершен')], default='new', max_length=32, verbose_name='Статус'),
        ),
    ]
