# Generated by Django 3.0.14 on 2021-08-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0033_auto_20210506_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['title'], 'verbose_name': 'Направление конкурса', 'verbose_name_plural': 'Направления конкурса'},
        ),
    ]
