# Generated by Django 3.0.14 on 2022-03-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_sum', models.IntegerField(max_length=255, verbose_name='Запрашиваемая сумма гранта')),
                ('sum_expenses', models.IntegerField(max_length=255, verbose_name='Сумма расходов')),
                ('source', models.CharField(max_length=255, verbose_name='Источник (источники)')),
                ('link', models.CharField(max_length=255, verbose_name='Сайт в сети Интернет')),
                ('recipient_type', models.CharField(max_length=255, verbose_name='Тип получателя софинансирования')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРН')),
                ('egryl_info', models.CharField(max_length=255, verbose_name='Сведения из ЕГРЮЛ')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('full_name_grantee', models.CharField(max_length=255, verbose_name='Полное наименование получателя гранта')),
                ('short_name_grantee', models.CharField(max_length=255, verbose_name='Сокращенное наименование получателя')),
                ('director', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('director_position', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
