# Generated by Django 3.0.14 on 2022-03-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='title',
            field=models.CharField(default=12412412, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
