# Generated by Django 3.0.14 on 2022-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0002_statement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='director',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='director_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='egryl_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сведения из ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='full_name_grantee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование получателя гранта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт в сети Интернет'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='ogrn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='recipient_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип получателя софинансирования'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='requested_sum',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='Запрашиваемая сумма гранта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='short_name_grantee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование получателя'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sum_expenses',
            field=models.IntegerField(blank=True, max_length=255, verbose_name='Сумма расходов'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
