# Generated by Django 3.0.14 on 2022-03-30 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mun_obr', '0003_auto_20220318_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='requested_sum',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='Запрашиваемая сумма гранта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник (источники)'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sum_expenses',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='Сумма расходов'),
        ),
    ]
