# Generated by Django 3.0.14 on 2022-05-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0004_auto_20220330_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_checking_account', models.CharField(blank=True, max_length=255)),
                ('c_bik', models.CharField(blank=True, max_length=255)),
                ('c_bank_name', models.CharField(blank=True, max_length=255)),
                ('c_correspondent_account', models.CharField(blank=True, max_length=255)),
                ('c_recipient_type', models.CharField(blank=True, max_length=255)),
                ('c_ogrn', models.CharField(blank=True, max_length=255)),
                ('c_full_org_name', models.CharField(blank=True, max_length=255)),
                ('c_short_org_name', models.CharField(blank=True, max_length=255)),
                ('c_jur_adress', models.CharField(blank=True, max_length=255)),
                ('c_fact_adress', models.CharField(blank=True, max_length=255)),
                ('c_inn', models.CharField(blank=True, max_length=255)),
                ('c_kpp', models.CharField(blank=True, max_length=255)),
                ('c_tel', models.CharField(blank=True, max_length=255)),
                ('c_mail', models.CharField(blank=True, max_length=255)),
                ('c_f_name', models.CharField(blank=True, max_length=255)),
                ('c_s_name', models.CharField(blank=True, max_length=255)),
                ('c_m_name', models.CharField(blank=True, max_length=255)),
                ('c_position', models.CharField(blank=True, max_length=255)),
                ('c_operates_on_the_basis', models.CharField(blank=True, max_length=255)),
                ('c_pdf_file', models.FileField(blank=True, upload_to='documents')),
                ('c_pdf_file_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
