# Generated by Django 3.0.14 on 2022-05-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0005_auto_20220509_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='c_statement',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='mun_obr.Statement'),
        ),
    ]
