# Generated by Django 3.0.14 on 2022-05-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0006_contract_c_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='c_statement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_statementOf', to='mun_obr.Statement'),
        ),
    ]
