# Generated by Django 3.0.14 on 2022-05-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0007_auto_20220511_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='director',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='director_position',
        ),
        migrations.AddField(
            model_name='statement',
            name='d_amount_of_overdue_debt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сумма просроченной задолженности'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_f_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_m_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Почта руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='d_s_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия руководителя'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tab_1_file_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Файл 1'),
        ),
    ]
