# Generated by Django 3.0.14 on 2022-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0008_auto_20220513_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('На доработка', 'На доработка'), ('Проверка пройдена', 'Проверка пройдена')], default='На модерации', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
