# Generated by Django 3.0.14 on 2022-05-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0011_messeges'),
    ]

    operations = [
        migrations.AddField(
            model_name='messeges',
            name='user_file',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
