# Generated by Django 3.0.14 on 2022-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0012_messeges_user_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mun_obr_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_go_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование МР/ГО')),
                ('main_fio', models.CharField(blank=True, max_length=255, verbose_name='ФИО лица, имеющего право подписи без доверенности')),
                ('sec_fio', models.CharField(blank=True, max_length=255, verbose_name='ФИО ответственного специалиста по взаимодействию с уполномоченным органом')),
                ('mail_jur', models.CharField(blank=True, max_length=255, verbose_name='Адрес электронной почты для направления юридически значимых документов;')),
                ('phone_2', models.CharField(blank=True, max_length=255, verbose_name='Контактный телефон')),
                ('ogrn', models.CharField(blank=True, max_length=255, verbose_name='ОГРН организации')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН организации')),
                ('jur_adrs', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('bank_data', models.CharField(blank=True, max_length=255, verbose_name='Банковские реквизиты ')),
            ],
        ),
    ]
