# Generated by Django 3.0.14 on 2022-05-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0013_mun_obr_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='tab_1_file_1',
            field=models.FileField(blank=True, max_length=255, upload_to='', verbose_name='Файл 1'),
        ),
    ]
