# Generated by Django 3.0.14 on 2022-05-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mun_obr', '0015_mun_obr_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mun_obr_profile',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statement',
            name='requested_sum',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Запрашиваемая сумма гранта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sum_expenses',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Сумма расходов'),
        ),
    ]
