# Generated by Django 3.0.14 on 2022-06-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0016_auto_20220531_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mun_obr_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='mun_obr_news/%Y/%m/%d', verbose_name='Картинка')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='Текст новости')),
            ],
        ),
    ]
