# Generated by Django 3.0.14 on 2022-06-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_obr', '0017_mun_obr_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='mun_obr_news',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
