# Generated by Django 3.0.6 on 2020-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20200512_1105'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='directions',
            field=models.ManyToManyField(blank=True, null=True, to='contest.Direction', verbose_name='Направления'),
        ),
    ]
