# Generated by Django 3.0.6 on 2020-05-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20200512_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('srednee_obshee', 'Среднее общее'), ('srednee_proff', 'Среднее профессиональное'), ('nezakonchennoe_vusshee', 'Не законченное высшее'), ('vusshee', 'Высшее'), ('bolee_odngogo_vishego', 'Более одного высшего'), ('uchenuy', 'Есть ученая степень')], max_length=32, verbose_name='Оразование'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.TextField(blank=True, null=True, verbose_name='Место работы (организация)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Женский'), ('M', 'Мужской')], max_length=1, verbose_name='Оразование'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рабочий телефон'),
        ),
    ]
