# Generated by Django 3.0.6 on 2020-05-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20200514_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Женский'), ('M', 'Мужской')], max_length=1, verbose_name='Пол'),
        ),
    ]
