# Generated by Django 3.0.6 on 2020-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20200514_1612'),
        ('profile', '0005_auto_20200514_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='directions',
            field=models.ManyToManyField(blank=True, to='contest.Direction', verbose_name='Направления'),
        ),
    ]
