# Generated by Django 3.0.6 on 2020-05-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200517_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
