# Generated by Django 3.0.14 on 2022-05-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20220316_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jur_adrs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail_jur',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='main_fio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mr_go_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sec_fio',
        ),
    ]
